package alex;

public enum ClaseLexica {
 VAR, INT, REAL, BOOL, TRUE, FALSE, VARIABLE, PAP, PCIERRE, IGUAL, PUNTOCOMA, NOT,DIFF, 
 IGIG, MAS, OR, MENOS, POR, DIV, EOF, AND, ANDAND, MENOR, MENIG, MAYIG, MAYOR
}
